from __future__ import annotations


PAD_X = 8
PAD_Y = 6
SECTION_PAD_Y = 16
TAB_PADDING = 16

LABEL_WIDTH = 22

SMALL_BUTTON_WIDTH = 12
MEDIUM_BUTTON_WIDTH = 16
LARGE_BUTTON_WIDTH = 20
EXTRA_LARGE_BUTTON_WIDTH = 24

TOP_ACTION_BUTTON_WIDTH = 12
TOP_SECONDARY_BUTTON_WIDTH = 18

WRAP_WIDTH_DEFAULT = 780
WRAP_WIDTH_WIDE = 820
WRAP_WIDTH_STATUS = 760